# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Luke Sonnet
#tagline:          'A Jekyll theme'
description:      'PhD Student, Political Science, UCLA'
url:              http://lukesonnet.github.io
baseurl:          /

author:
  name:           'Luke Sonnet'
  url:            https://twitter.com/LukeSonnet

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/lukesonnet/lukesonnet.github.io
