# Dependencies
markdown:         kramdown
gems:             [jekyll-paginate]

# Permalinks
permalink:        pretty
highlight:        pygments
# Setup
title:            Luke Sonnet
description:      'PhD Student, Political Science, UCLA'
url:              http://lukesonnet.github.io

author:
  name:           'Luke Sonnet'
  url:            https://twitter.com/LukeSonnet

paginate:         1
paginate_path:    "/thoughts/page:num"
# Custom vars
#version:          2.1.0

#github:
#  repo:           https://github.com/lukesonnet/lukesonnet.github.io
